/** Expanded static fun content (English) */

const JOKES = [
  'Why do programmers prefer dark mode? Because light attracts bugs.',
  'There are only 10 kinds of people: those who understand binary and those who do not.',
  'A SQL query walks into a bar, walks up to two tables and asks: can I join you?',
  'Why do Java developers wear glasses? Because they cannot C#.',
  'I would tell you a UDP joke, but you might not get it.',
  'How many programmers does it take to change a light bulb? None, that is a hardware problem.',
  'Why did the developer go broke? Because he used up all his cache.',
  'A programmer had a problem and thought: I know, I will use threads. Now has two problems.',
  'Why do Python programmers wear glasses? Because they cannot C.',
  'Real programmers count from 0.',
  'There is no place like 127.0.0.1.',
  'I do not always test my code, but when I do, I do it in production.',
  'Algorithm: word used by programmers when they do not want to explain what they did.',
  'Why was the JavaScript developer sad? Because he did not Node how to Express himself.',
  'Debugging: being the detective in a crime movie where you are also the murderer.',
  'Copy-paste was invented by a lazy programmer and perfected by a stack overflow user.',
  'A good programmer is someone who looks both ways before crossing a one-way street.',
  'Hardware: the part of a computer you can kick when the software fails.',
  'Why do programmers hate nature? It has too many bugs and no undo button.',
  'Git commit -m "fix" — the most popular lie in software development.',
  'Programmer: machine that turns coffee into code.',
  'Why did the function break up with the variable? It needed more space.',
  'Documentation is like a love letter to your future self.',
  'Weeks of coding can save you hours of planning.',
  'In theory, theory and practice are the same. In practice, they are not.',
];

const ROASTS = [
  'your Wi-Fi has more presence than you.',
  'you have the charisma of a 404 error.',
  'even airplane mode finds you distant.',
  'your aura buffers too hard.',
  'you are the human equivalent of a loading spinner.',
  'if confidence was Wi-Fi, you would be on 1 bar.',
  'you bring the same energy as a muted mic.',
  'your personality runs on demo mode.',
  'you are proof that autocorrect cannot fix everything.',
  'you have main-character energy in a background NPC role.',
  'your comeback game is still compiling.',
  'you are like a free trial that nobody upgraded.',
  'your vibe is "please hold" music.',
  'you are the plot twist nobody asked for.',
  'your social battery is permanently at 1%.',
  'you are the reason group chats go quiet.',
  'your luck stat is clearly set to zero.',
  'you type like you are paying per letter.',
  'you are the tutorial level everyone skips.',
  'your timing is as good as a Discord ping at 3 AM.',
  'you are built like a side quest with no reward.',
  'your confidence and your internet history should never meet.',
  'you are one brain cell away from a system reboot.',
  'your energy says "read" but your message says "sent from my couch".',
  'you are the human version of "connection unstable".',
];

const COMPLIMENTS = [
  'you make this server better.',
  'you have legendary vibes.',
  'keep doing exactly what you are doing.',
  'your presence upgrades every channel.',
  'you are genuinely fun to have around.',
  'the server is lucky to have you.',
  'you have top-tier energy.',
  'you are cooler than a fresh ping.',
  'your humor hits more often than it misses.',
  'you are the kind of person people want in their squad.',
  'you bring good chaos in the best way.',
  'you are built different — in a good way.',
  'your vibe is certified premium.',
  'you make ordinary days feel less ordinary.',
  'you are proof that nice people still exist online.',
  'your personality has no lag.',
  'you are a W and everyone knows it.',
  'you radiate main-character energy the right way.',
  'talking to you is never a waste of time.',
  'you are one of the good ones — seriously.',
  'your taste is suspiciously excellent.',
  'you are the reason some people stay in the server.',
  'you have big "reliable friend" energy.',
  'you are underrated and it shows.',
  'you make the internet slightly less cursed.',
];

const EIGHT_BALL = [
  'Yes.',
  'No.',
  'Maybe.',
  'Without a doubt.',
  'Very likely.',
  'Ask again later.',
  'Signs point to yes.',
  'Absolutely not.',
  'Concentrate and ask again.',
  'Clearly yes.',
  'Outlook good.',
  'Do not count on it.',
  'My sources say no.',
  'It is certain.',
  'Reply hazy, try again.',
  'Yes, definitely.',
  'Better not tell you now.',
  'Cannot predict now.',
  'Most likely.',
  'Very doubtful.',
  'As I see it, yes.',
  'As I see it, no.',
  'Yes, in due time.',
  'Signs point to no.',
  'You may rely on it.',
];

const WOULD_YOU_RATHER = [
  ['Have unlimited pizza', 'Have unlimited tacos'],
  ['Always be 10 minutes late', 'Always be 20 minutes early'],
  ['Fight one horse-sized duck', 'Fight 100 duck-sized horses'],
  ['Never use social media again', 'Never watch videos again'],
  ['Be able to fly', 'Be able to breathe underwater'],
  ['Live without music', 'Live without movies'],
  ['Know how you die', 'Know when you die'],
  ['Always speak your mind', 'Never speak again'],
  ['Be famous for 15 minutes', 'Be rich but unknown'],
  ['Have perfect memory', 'Forget anything you want on command'],
  ['Only eat sweet food', 'Only eat savory food'],
  ['Teleport anywhere instantly', 'Time travel but only once'],
  ['Win the lottery once', 'Have your dream job forever'],
  ['Always win arguments', 'Always avoid conflict'],
  ['Read minds', 'See the future'],
  ['Live in a cabin in the woods', 'Live in a penthouse in the city'],
  ['Never need sleep', 'Never need food'],
  ['Be the funniest person in the room', 'Be the smartest person in the room'],
  ['Have a rewind button for life', 'Have a pause button for life'],
  ['Always tell the truth', 'Always get away with lies'],
  ['Explore space', 'Explore the deep ocean'],
  ['Be able to talk to animals', 'Speak every human language'],
  ['Have free Wi-Fi everywhere', 'Have free coffee everywhere'],
  ['Relive the same day once', 'Skip one day of your life forever'],
  ['Never use emojis again', 'Never use GIFs again'],
];

const FACTS_FALLBACK = [
  'Honey never spoils. Archaeologists have found edible honey in ancient tombs.',
  'Octopuses have three hearts and blue blood.',
  'A group of flamingos is called a flamboyance.',
  'Bananas are berries, but strawberries are not.',
  'The shortest war in history lasted 38 to 45 minutes.',
  'Sharks existed before trees.',
  'A day on Venus is longer than a year on Venus.',
  'Wombat poop is cube-shaped.',
  'The Eiffel Tower can grow taller in summer due to heat expansion.',
  'There are more possible chess games than atoms in the observable universe.',
];

const QUOTES_FALLBACK = [
  { content: 'The only way to do great work is to love what you do.', author: 'Steve Jobs' },
  { content: 'In the middle of difficulty lies opportunity.', author: 'Albert Einstein' },
  { content: 'It does not matter how slowly you go as long as you do not stop.', author: 'Confucius' },
  { content: 'Stay hungry, stay foolish.', author: 'Steve Jobs' },
  { content: 'The best time to plant a tree was 20 years ago. The second best time is now.', author: 'Chinese proverb' },
  { content: 'Not all those who wander are lost.', author: 'J.R.R. Tolkien' },
  { content: 'Simplicity is the ultimate sophistication.', author: 'Leonardo da Vinci' },
  { content: 'Fortune favors the bold.', author: 'Virgil' },
];

const HANGMAN_WORDS = [
  'discord', 'javascript', 'python', 'developer', 'keyboard', 'monitor',
  'network', 'server', 'database', 'function', 'variable', 'algorithm',
  'internet', 'password', 'security', 'channel', 'message', 'emoji',
  'moderator', 'giveaway', 'ticket', 'welcome', 'banana', 'penguin',
  'rocket', 'galaxy', 'coffee', 'midnight', 'sunshine', 'adventure',
];

const TRIVIA_FALLBACK = [
  {
    question: 'What does HTML stand for?',
    correct: 'HyperText Markup Language',
    incorrect: ['HighText Machine Language', 'HyperTool Multi Language', 'HomeTool Markup Language'],
  },
  {
    question: 'Which planet is known as the Red Planet?',
    correct: 'Mars',
    incorrect: ['Venus', 'Jupiter', 'Saturn'],
  },
  {
    question: 'What is the capital of France?',
    correct: 'Paris',
    incorrect: ['London', 'Berlin', 'Madrid'],
  },
  {
    question: 'How many continents are there on Earth?',
    correct: '7',
    incorrect: ['5', '6', '8'],
  },
  {
    question: 'What year did the first iPhone release?',
    correct: '2007',
    incorrect: ['2005', '2008', '2010'],
  },
];

const RATE_COMMENTS = [
  'Solid choice.',
  'Interesting pick.',
  'Certified classic.',
  'Mid at best.',
  'Absolute legend tier.',
  'Needs more seasoning.',
  'Surprisingly respectable.',
  'Chaos energy detected.',
  'Would recommend to a friend.',
  'Big mood.',
  'Objectively questionable.',
  'Top 1% material.',
  'Built different.',
  'Peak performance.',
  'Room for improvement.',
];

module.exports = {
  JOKES,
  ROASTS,
  COMPLIMENTS,
  EIGHT_BALL,
  WOULD_YOU_RATHER,
  FACTS_FALLBACK,
  QUOTES_FALLBACK,
  HANGMAN_WORDS,
  TRIVIA_FALLBACK,
  RATE_COMMENTS,
};
